name: SonarCloud Org Repo Scan
description: >
  Scan your code with SonarCloud to detect bugs, vulnerabilities and code smells
  in 26+ programming languages.
branding:
  icon: check
  color: green

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  SonarCloud:
    name: "SonarCloud"
    steps:
      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-session-name: ${{ inputs.devops_role_session_name }}
          role-to-assume: ${{ inputs.devops_role_assume }}
          aws-region: ${{ inputs.devops_artifact_region }}
          role-duration-seconds: 1200

      - name: Docker action
        runs:
          using: docker
          image: Dockerfile
          entrypoint: "/entrypoint.sh"
          post-entrypoint: "/cleanup.sh"

inputs:
  args:
    description: Additional arguments to the sonarcloud scanner
    required: false
  projectBaseDir:
    description: Set the sonar.projectBaseDir analysis property
    required: false
    default: .
  devops_role_session_name:
    type: string
    required: false
    default: nocnoc-github-session
  devops_role_assume:
    type: string
    required: false
    default: arn:aws:iam::885420015722:role/pipeline-sonar-cloud-role
  devops_artifact_region:
    type: string
    required: false
    default: ap-southeast-1
